### ISSUE TITLE
Config changes of checkboxes doesn't get saved / transfered to the T2

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerAir#10]
Looks like unchecking of a checked checkbox isn't correctly saved and i doesn't get tranfered to the T2.

I tried it with my "rapidfire app" script.

try 1:
"Rapidfire on Start"
leaving it disabled after download "Load and Run" will leave it disabled correctly, LED red

try 2:
"Rapidfire on Start"
checked and "Load and Run" will enable it correctly, LED green.

try 3:
"Rapidfire on Start"
uncheck it and hit "Load and Run" will still leave it enabled at the T2, LED green.
If it really gets disabled the script will change the LED to red.

Closing the Script on the App via [X] and reopen it will show the "Rapidfire on Start" still as checked..so it didn't get saved correctly ?

**Comment by PablosScripts** [comment]
I just observed this myself. I was pulling my hair out trying to figure out what was wrong with my script and realised the mismatch between app settings when I compared it with my PC.

**Comment by J2Kbr** [comment]
Bug Fixed on Gtuner Air 1.10
