### ISSUE TITLE
speech notification not working on GTuner Air

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerAir#14]
It works fine with GTuner IV, but with GTuner Air on Iphone 5s (ios 12.4.4) it is not working for me.
For bonefisher it isn't working on android: https://www.consoletuner.com/forum/viewtopic.php?f=26&t=14617&p=94845#p94836

Any chance that this is caused by missing permissions ?
GTuner Air doesn't seem to ask/activate the bluetooth on its own. I have to enable that manually first if it is disabled at the start of the program. Maybe the app is lacking permission rights to access the audio on the phones ?

**Comment by J2Kbr** [comment]
Fixed on Gtuner Air 1.20
