### ISSUE TITLE
Feature Request: A T2 Loaded Slot Panel monitor and info display to GTuner Air to use mobile phone as visual display of loaded game pack or script information

### ISSUE THREAD

**Issue by cwiggy78** [J2Kbr/GtunerAir#17]
Feature Request.

This would allow users of the T2 to visually monitor the T2 Slot loaded with a gamepack (or script) whilst in game.

So for example in a Call of duty script if a script is loaded which contains weapon presets,  as the presets are swapped within the gamepack the parameters and embedded information is displayed on a screen within GTuner Air for that T2 slot.  Maybe in the GTuner air GUI you could be able to set and edit information to be displayed like certain weapon names, Anti Recoil values etc or alternatively all of this information could be setup within the gamepack or script and GTuner Air just displays the information as it's triggered within the script or slot.

The possibilities seem endless with this.   It would make use of the fact that everyone has a mobile phone display next to them and the T2 when playing so why not develop this feature within the GTuner Air app that already talks to the T2 ??.

Really excited about this J2Kbr. Please develop this feature.

**Comment by cwiggy78** [comment]
To add I think this has also been requested on the forums by ximco and is somewhat tied to:

Feature Request: Adding the output panel to Gtuner air #16

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner Air 1.22, to be released soon.
