### ISSUE TITLE
In the PC based Interactive Configurator "quotation" marks are fine, however they get all messed up in the mobile version.

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerAir#6]

**Comment by J2Kbr** [comment]
Not sure if I fully understood the issue. I see several Configuration Descriptors with quotation in the description field, showing as expected. If you still have this problem, please post a screenshot so I can have a better understanding of the issue. Thank you.

**Comment by Scachi** [comment]
Using " in item = .. seems to be the problem
This shows up correctly in GTuner IV but shows up as html tag in GTuner Air
```
/*
<cfgdesc>
[Example]
group       = true
control     = combobox
byteoffset  = 3
bitsize     = 8
shortdesc	  = <<<MULTILINE
<b><font color="DarkViolet">____RECORDING____</font>
<font color="DarkViolet">Start recording</b> on action:</b></font>
MULTILINE
default     = 1
item        = 0) Press: Button "Alpha"
item        = 1) Holding down: Button "Alpha"
item        = 2) Double Tap: Button "Alpha"
item        = 3) Hold: Button "Alpha" and Tap: Button "Beta"
</cfgdesc>
*/
```
GTuner IV:
![image](https://user-images.githubusercontent.com/22262242/66612630-af600880-ebc2-11e9-8377-5d6871cca8b1.png)

GTuner Air:
![image](https://user-images.githubusercontent.com/22262242/66612814-796f5400-ebc3-11e9-9f96-32f8df262d35.png)
