### ISSUE TITLE
The "review" bar needs a rethink

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerAir#9]
I think it's time to rethink the "up vote" interface. Once you go beyond 10 it loses its meaning and it also takes up too much screen real estate. This is a quick mockup of an alternative view: 

https://i.imgur.com/7hAdjsP.png

The current design of 13 / 2236 will be very confusing for new users. It makes it look like there's a quota of 2236 stock!

That being said mine is a mockup only, I probably wouldn't go with the down arrow to indicate number of downloads...this might be confused for a download button. I'm not sure what other iconography would work. But hopefully it gets my point across.

**Comment by J2Kbr** [comment]
Tried add icons to this line for better represent the meaning of the values. Unfortunately, the line height is too small, the icons ended unrecognizable. I will still find a better solution, for now the `/` was replaced by `|`. Thanks.
